---
- name: set dhcp-configs
  include: set_dhcp_config.yml
  vars:
    interface: "{{item.interface}}"
    leasetime: "{{item.leasetime | default({})}}"
    limit: "{{item.limit | default({})}}"
    start: "{{item.start | default({})}}"
  with_items: "{{dhcp_configs}}"

- name: set dhcp-hosts
  include: set_dhcp_host.yml
  vars:
    index: "{{item.1.index | default(item.0)}}"
    name: "{{item.1.name}}"
    mac: "{{item.1.mac}}"
    ip: "{{item.1.ip}}"
  with_indexed_items: "{{dhcp_hosts}}"
